config/routes.rb
Rails.application.routes.draw do
  # get 'equipments/index'
  # get 'equipments/show'
  # get 'equipments/new'
  # get 'equipments/edit'
  # get 'equipments/delete'
  # get 'equipments/equip_list'
  # get 'reservations/index'
  # get 'reservations/show'
  # get 'reservations/new'
  # get 'reservations/edit'
  # get 'reservations/delete'
  # get 'users/index'
  # get 'users/show'
  # get 'users/new'
  # get 'users/edit'
  # get 'users/delete'

  root to: "home#index"
  get 'home/index'
  
  devise_for :accounts
  
  # EQUIPMENT ROUTES (Non ID routes cannot go into rescources)
  get 'equipments/index'
  get 'equipments/equip_list'
  resources :equipments do
    member do
      get :check_out
      get :check_in
      get :show_for_members
      get :delete
    end
  end
 
  # RESERVATION ROUTES
  # get 'reservations/select_date'
  post 'reservations/equip_reserve'
  get 'reservations/reservation_log'
  get 'reservations/future_reservations'
  get 'reservations/reserve_item'
  get 'reservations/reservation_list'
  resources :reservations do
    member do
      get :delete
      get :cancel_item
      get :admin_cancel_item
    end
  end

  resources :users do
    member do
      get :delete
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  # Establish Relationship
  belongs_to :reservation, optional: true

  # Scope Testing of Equipment Model
  scope :avail_items, -> { where(available: true) }
  scope :not_avail_items, -> { where(available: false) }

  # Validation Testing of Equipment Model
  validates :name, presence: true
  validates :description, presence: true
  # validates :available, presence: true
  validates :available, inclusion: [true, false]
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  require 'date'

  # Account Authorization
  def auth_admin
    redirect_to(root_path) unless current_account.is_admin
  end

  # Run auth befor all actions
  before_action :authenticate_account!
  before_action :auth_admin, only: %i[index show new create edit update delete destroy]

  ##################################################################################################

  # Only Accessible By Admin
  def index
    @equipments = Equipment.order('id ASC')
  end

  # Only Accessible By Admin
  def show
    @equipment = Equipment.find(params[:id])
  end

  # Only Accessible By Admin
  def new
    @equipment = Equipment.new
  end

  # Only Accessible By Admin
  def create
    @equipment = Equipment.new(equipment_params)
    if @equipment.save
      redirect_to(equipments_path)
    else
      render('new')
    end
  end

  # Only Accessible By Admin
  def edit
    @equipment = Equipment.find(params[:id])
  end

  # Only Accessible By Admin
  def update
    @equipment = Equipment.find(params[:id])
    if @equipment.update(equipment_params)
      redirect_to(equipment_path(@equipment))
    else
      render('edit')
    end
  end

  # Only Accessible By Admin
  def delete
    @equipment = Equipment.find(params[:id])
  end

  # Only Accessible By Admin
  def destroy
    @equipment = Equipment.find(params[:id])
    @equipment.destroy
    redirect_to(equipments_path)
  end

  def equip_list
    @equipments = Equipment.order('id ASC')
    @equipments.each do |item|
      next unless !item.reservation.nil? && Account.find_by(id: item.reservation.account_id).nil?

      # Break the link to its current reservation
      item.reservation_id = nil
      item.save
      item.update(available: true)
    end
    render('equipments/equip_list')
  end

  # Make Secure For Error Catching
  def check_out
    invalid_item = false
    @equipment = Equipment.find(params[:id])

    # Cant check out if its already checked out.
    invalid_item = true if !@equipment.reservation_id.nil? && (@equipment.available == false)

    if invalid_item
      redirect_to(equipments_equip_list_path)
      flash[:alert] = 'Notice: That item is already checked out!'
    else
      # Find current account and the wanted item
      @acc_id = current_account.id
      @current_time = DateTime.now
      @return_time = @current_time + 7

      # Make a new reservation, set owner as the current user
      @reservation = Reservation.new(account_id: @acc_id, checkout_date: @current_time, checkin_date: @return_time)
      @reservation.save

      # Set equipment FK to the just made reservation
      @equipment.reservation = @reservation

      # Protect
      @equipment.save

      # Update Item Info For Equipment Log
      @reservation.update(saved_item: @equipment.name)
      @reservation.update(renter_name: current_account.first_name + ' ' + current_account.last_name)

      # Update its availability
      @equipment.update(available: false)
      redirect_to(show_for_members_equipment_path(@equipment))

      # Sends the user an email confirming the check out
      ReservationMailer.checkout_reservation(@equipment, current_account).deliver_now
    end
  end

  # Make Secure For Error Catching
  def check_in
    # Check if the item is checked out and belongs to the signed in user.
    @equipment = Equipment.find(params[:id])
    can_check_in = false

    # If checked out
    # If belongs to current user
    if !@equipment.reservation_id.nil? && (@equipment.available == false)
      res_obj = Reservation.find(@equipment.reservation_id)
      can_check_in = true if (res_obj.account_id == current_account.id) && (res_obj.saved_item == @equipment.name)
    end

    if can_check_in

      # Check if item is overdue and send email and increase violation count
      if DateTime.now > @equipment.reservation.checkin_date
        ReservationMailer.overdue_reservation(@equipment, current_account).deliver_now
        @new_violation_count = @equipment.reservation.account.violation_counter + 1
        @acc = Account.where(id: current_account.id)
        @acc.update(violation_counter: @new_violation_count)
      end

      # Break the link to its current reservation
      @equipment.reservation_id = nil
      @equipment.save
      @equipment.update(available: true)

      redirect_to(show_for_members_equipment_path(@equipment))

      # Sends the user an email confirming the check in
      ReservationMailer.checkin_reservation(@equipment, current_account).deliver_now

    else
      redirect_to(equipments_equip_list_path)
      flash[:alert] = 'Notice: That item is not checked out or does not belong to you!'
    end
  end

  def show_for_members
    @equipment = Equipment.find(params[:id])
    render('equipments/member_show')
  end

  def equipment_params
    params.require(:equipment).permit(:name, :description, :available)
  end
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/views/equipments/_form.html.erb
<table summary="Equipment form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= f.text_field(:description) %></td>
  </tr>
  <tr>
    <th>Available</th>
    <td><%= f.select(:available, options_for_select([['Yes', true], ['No', false]]), { include_blank: false }) %></td>
  </tr>
</table>

app/views/equipments/delete.html.erb
<% flash.each do |type, msg| %>
    <div style="color:red;">
    <%= msg %>
    </div>
<% end %>

<style>
body {
  background-color: rgb(200, 200, 200);
  opacity: 0.9;
  color: black;
}
table.listing {
  margin-left:auto;
  margin-right:auto;
  color: black;
}
</style>

<h2 style = "text-align: center; margin-top:30px;">Admin | Delete Equipment Item</h2>
<br/>


<center>
<div class="container" style="width: 400px; margin: auto; background-color: rgb(230, 230, 230); 
  border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000; padding-bottom:15px; padding-top:15px;">
  <div class="equipments delete">

    <%= form_for(@equipment, :method => 'delete') do |f| %>
      <p>Are you sure you want to delete: <%= @equipment.name %></p>

      <div class="form-buttons">
        <%= f.submit("Delete equipment") %>
      </div>

    <% end %>
    
  </div>
</div>
</center>
<br/>

<div style = "text-align: center; padding-bottom:20px;"> 
  <%= link_to("<< Back to Equipment List", equipments_path, :class => 'back-link') %>
</div>
<br/>

app/views/equipments/edit.html.erb
<% flash.each do |type, msg| %>
    <div style="color:red;">
    <%= msg %>
    </div>
<% end %>

<style>
body {
  background-color: rgb(200, 200, 200);
  opacity: 0.9;
  color: black;
}
table.listing {
  margin-left:auto;
  margin-right:auto;
  color: black;
}
</style>

<h2 style = "text-align: center; margin-top:30px;">Admin | Edit Equipment Item</h2>
<br/>

<center>
<div class="container" style="width: 400px; margin: auto; background-color: rgb(230, 230, 230); 
    border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000; padding-bottom:15px; padding-top:15px;">
  <div class="equipments edit">

    <%= form_for(@equipment) do |f| %>
      
      <%= render(:partial => 'form', :locals => {:f => f}) %>

      <div class="form-buttons">
        <%= f.submit("Update Equipment") %>
      </div>

    <% end %>
  </div>
</div>
</center>
<br/>

<div style = "text-align: center; padding-bottom:20px;"> 
  <%= link_to("<< Back to Equipment List", equipments_path, :class => 'back-link') %>
</div>
<br/>

app/views/equipments/equip_list.html.erb
<% flash.each do |type, msg| %>
    <div style="color:red;">
    <%= msg %>
    </div>
<% end %>
<br/>

<style>
body {
  background-color: rgb(200, 200, 200);
  opacity: 0.9;
  color: black;
}
table.listing {
  margin-left:auto;
  margin-right:auto;
  color: black;
}
</style>

<h1 style="text-align: center; margin-top:30px;">Equipment Check In / Check Out</h1>
<br/>

<center>
<div class="container" style="width: 1200px; margin: auto; background-color: rgb(230, 230, 230); 
    border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000; padding-bottom:15px; padding-top:15px;">
    <div class="equipments equip_list">
        <table class="listing" summary="equipment list">
            <tr class="header">
                <th style="padding:0 15px;"> ID </th>
                <th style="padding:0 15px;"> Name </th>
                <th style="padding:0 15px;"> Description </th>
                <th style="padding:0 15px;"> Available </th>
                <th style="padding:0 15px;"> Current User </th>
                <th style="padding:0 15px;"> Date Checked Out </th>
                <th style="padding:0 15px;"> Return By Date </th>
                <th style="padding:0 15px;"> Actions </th>
            </tr>
            <% @equipments.each do |equipment| %>
            <tr>
                <td style="padding:0 15px;"><%= equipment.id%></td>
                <td style="padding:0 15px;"><%= equipment.name%></td>
                <td style="padding:0 15px;"><%= equipment.description%></td>
                <td style="padding:0 15px;"><%= equipment.available%></td>

                <td style="padding:0 15px;">
                <% if equipment.reservation%>
                <%= equipment.reservation.account.email %>
                <% end %>
                </td>

                <td style="padding:0 15px;">            
                <% if equipment.reservation%>
                <%= equipment.reservation.checkout_date %>
                <% end %>
                </td>

                <td style="padding:0 15px;">            
                <% if equipment.reservation%>
                <%= equipment.reservation.checkin_date %>
                <% end %>
                </td>

                <td style="padding:0 15px;"class="actions">
                    <%= link_to("Check In", check_in_equipment_path(equipment), :class => "action check_out") %>
                    <%= link_to("Check Out", check_out_equipment_path(equipment), :class => "action check_in") %>
                </td>
            </tr>
            <% end %>
        </table>
    </div>
</div>
</center>
<br/>


<h4 style="text-align: center; margin-top:30px;">My Checked Out Items</h4>
<br/>

<center>
<div class="container" style="width: 1050px; margin: auto; background-color: rgb(230, 230, 230); 
    border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000; padding-bottom:15px; padding-top:15px;">
    <div class="my equipments">
        <table class="listing" summary="Equipment List">
            <tr class="header">
                <th style="padding:0 15px;"> ID </th>
                <th style="padding:0 15px;"> Name </th>
                <th style="padding:0 15px;"> Description </th>
                <th style="padding:0 15px;"> Date Checked Out </th>
                <th style="padding:0 15px;"> Return By Date </th>
            </tr>
            <% current_account.equipments.each do |equipment| %>
            <tr>
                <td style="padding:0 15px;"><%= equipment.id%></td>
                <td style="padding:0 15px;"><%= equipment.name%></td>
                <td style="padding:0 15px;"><%= equipment.description%></td>
                
                <td style="padding:0 15px;">            
                <% if equipment.reservation%>
                <%= equipment.reservation.checkout_date %>
                <% end %>
                </td>

                <td style="padding:0 15px;">            
                <% if equipment.reservation%>
                <%= equipment.reservation.checkin_date %>
                <% end %>
                </td>
            </tr>
            <% end %>
        </table>
    </div>
</div>
</center>
<br/>

app/views/equipments/index.html.erb
<% flash.each do |type, msg| %>
    <div style="color:red;">
    <%= msg %>
    </div>
<% end %>


<style>
body {
  background-color: rgb(200, 200, 200);
  opacity: 0.9;
  color: black;
}
table.listing {
  margin-left:auto;
  margin-right:auto;
  color: black;
}
</style>

<h1 style="text-align: center; margin-top:30px;">Admin Equipment Management</h1>
<br/>

<center>
<div class="container" style="width: 750px; margin: auto; background-color: rgb(230, 230, 230); 
    border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000; padding-bottom:15px; padding-top:15px;">
    <div class="equipments index">
        <%= link_to("ADD NEW EQUIPMENT", new_equipment_path, :class => "action new")%>
        <table class="listing" summary="Equipment List">
            <tr class="header">
                <th style="padding:0 15px;"> ID </th>
                <th style="padding:0 15px;"> Name </th>
                <th style="padding:0 15px;"> Description </th>
                <th style="padding:0 15px;"> Available </th>
                <th style="padding:0 15px;"> Actions </th>
            </tr>
            <% @equipments.each do |equipment| %>
            <tr>
                <td style="padding:0 15px;"><%= equipment.id%></td>
                <td style="padding:0 15px;"><%= equipment.name%></td>
                <td style="padding:0 15px;"><%= equipment.description%></td>
                <td style="padding:0 15px;"><%= equipment.available %> </td>
                <td style="padding:0 15px;" class="actions">
                    <%= link_to("Show", equipment_path(equipment), :class => "action show") %>
                    <%= link_to("Edit", edit_equipment_path(equipment), :class => "action edit") %>
                    <%= link_to("Delete", delete_equipment_path(equipment), :class => "action delete") %>
                </td>
            </tr>
            <% end %>
        </table>
    </div>
</div>
</center>
<br/>

<div style = "text-align: center; padding-bottom:20px;">
    <%= link_to("<< Back To Dashboard", edit_account_registration_path, :class => 'action equip_list')%>
</div>
<br/>

app/views/equipments/member_show.html.erb
<style>
body {
  background-color: rgb(200, 200, 200);
  opacity: 0.9;
  color: black;
}
table.listing {
  margin-left:auto;
  margin-right:auto;
  color: black;
}
</style>

<h2 style="text-align: center; margin-top:30px;">Equipment Item Info</h2>
<br/>

<center>
<div class="container" style="width: 300px; margin: auto; background-color: rgb(230, 230, 230); 
  border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000; padding-bottom:15px; padding-top:15px;">

  <div class="equipments show">
    <table summary="equipment detail view">
      <tr>
        <th>ID</th>
        <td><%= @equipment.id %></td>
      </tr>
      <tr>
        <th>Name</th>
        <td><%= @equipment.name %></td>
      </tr>
      <tr>
        <th>Description</th>
        <td><%= @equipment.description%></td>
      </tr>
      <tr>
        <th>Available</th>
        <td><%= @equipment.available %></td>
      </tr>
    </table>
  </div>
</div>
</center>
<br/>

<div style = "text-align: center; padding-bottom:20px;">
  <%= link_to("<< Back to Equipment", equipments_equip_list_path, :class => 'back-link') %>
</div>

app/views/equipments/new.html.erb
<style>
body {
  background-color: rgb(200, 200, 200);
  opacity: 0.9;
  color: black;
}
table.listing {
  margin-left:auto;
  margin-right:auto;
  color: black;
}
</style>

<h2 style = "text-align: center; margin-top:30px;">Equipment Create</h2>
<br/>

<center>
<div class="container" style="width: 400px; margin: auto; background-color: rgb(230, 230, 230); 
    border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000; padding-bottom:15px; padding-top:15px;">
    <div class="equipments new">
      <h3>Create an Equipment Item</h3>

      <%= form_for(@equipment, :url => equipments_path, :method => 'post') do |f| %>

        <%= render(:partial => 'form', :locals => {:f => f}) %>

        <div class="form-buttons">
          <%= f.submit("Create Equipment") %>
        </div>

      <% end %>
    </div>
</div>
</center>
<br/>

<div style = "text-align: center; padding-bottom:20px;">  
  <%= link_to("<< Back to Equipment List", equipments_path, :class => 'back-link') %>
</div>
<br/>

app/views/equipments/show.html.erb
<% flash.each do |type, msg| %>
    <div style="color:red;">
    <%= msg %>
    </div>
<% end %>

<style>
body {
  background-color: rgb(200, 200, 200);
  opacity: 0.9;
  color: black;
}
table.listing {
  margin-left:auto;
  margin-right:auto;
  color: black;
}
</style>

<h2 style = "text-align: center; margin-top:30px;">Admin | Equipment Item Info</h2>
<br/>

<center>
<div class="container" style="width: 300px; margin: auto; background-color: rgb(230, 230, 230); 
    border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000; padding-bottom:15px; padding-top:15px;">
  <div class="equipments show">
    <table summary="equipment detail view">
      <tr>
        <th>ID</th>
        <td><%= @equipment.id %></td>
      </tr>
      <tr>
        <th>Name</th>
        <td><%= @equipment.name %></td>
      </tr>
      <tr>
        <th>Description</th>
        <td><%= @equipment.description%></td>
      </tr>
      <tr>
        <th>Available</th>
        <td><%= @equipment.available %></td>
      </tr>
      
    </table>
  </div>
</div>
</center>
<br/>

<div style = "text-align: center; padding-bottom:20px;"> 
  <%= link_to("<< Back to Equipment List", equipments_path, :class => 'back-link') %>
</div>
<br/>