config/routes.rb
Rails.application.routes.draw do
  # get 'equipments/index'
  # get 'equipments/show'
  # get 'equipments/new'
  # get 'equipments/edit'
  # get 'equipments/delete'
  # get 'equipments/equip_list'
  # get 'reservations/index'
  # get 'reservations/show'
  # get 'reservations/new'
  # get 'reservations/edit'
  # get 'reservations/delete'
  # get 'users/index'
  # get 'users/show'
  # get 'users/new'
  # get 'users/edit'
  # get 'users/delete'

  root to: "home#index"
  get 'home/index'
  
  devise_for :accounts
  
  # EQUIPMENT ROUTES (Non ID routes cannot go into rescources)
  get 'equipments/index'
  get 'equipments/equip_list'
  resources :equipments do
    member do
      get :check_out
      get :check_in
      get :show_for_members
      get :delete
    end
  end
 
  # RESERVATION ROUTES
  # get 'reservations/select_date'
  post 'reservations/equip_reserve'
  get 'reservations/reservation_log'
  get 'reservations/future_reservations'
  get 'reservations/reserve_item'
  get 'reservations/reservation_list'
  resources :reservations do
    member do
      get :delete
      get :cancel_item
      get :admin_cancel_item
    end
  end

  resources :users do
    member do
      get :delete
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Account Authorization
  def auth_admin
    redirect_to(root_path) unless current_account.is_admin
  end

  # Run auth befor all actions
  before_action :authenticate_account!
  before_action :auth_admin

  ####################################

  # Only for admins
  def index
    @users = Account.order('id ASC')
  end

  # Only for admins
  def show
    @user = Account.find(params[:id])
  end

  # Should stay Empty
  def new; end

  # Should stay empty
  def create; end

  # Only for admins
  def edit
    @user = Account.find(params[:id])
  end

  # Only for admins
  def update
    @user = Account.find(params[:id])
    if @user.update(user_params)
      redirect_to(users_path)
      flash[:alert] = 'Notice: User successfully edited.'
    else
      flash[:alert] = 'Notice: Error when updating user.'
      render('edit')
    end
  end

  # Only for admins
  def delete
    @user = Account.find(params[:id])
  end

  # Only for admins
  def destroy
    @user = Account.find(params[:id])
    @user.destroy
    redirect_to(users_path)
    flash[:alert] = 'Notice: Account deleted successfully.'
  end

  private

  def user_params
    params.require(:account).permit(:email, :first_name, :last_name, :phone_number, :secondary_contact, :is_admin, :violation_counter)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/delete.html.erb
<% flash.each do |type, msg| %>
    <div style="color:red;">
    <%= msg %>
    </div>
<% end %>

<style>
body {
  background-color: rgb(200, 200, 200);
  opacity: 0.9;
  color: black;
}
table.center {
  margin-left:auto;
  margin-right:auto;
  color: black;
}
</style>

<h2 style="text-align: center; margin-top:30px;">Admin | Delete Selected User</h2>
<br/>

<center>
<div class="container" style="width: 410px; margin: auto; background-color: rgb(230, 230, 230); 
    border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000; padding-top:15px; padding-bottom:15px;">
    <div>
        <%= form_for(@user, url: {action: "destroy"}, :method => 'delete') do |f| %>
            <p>Are you sure you want to delete this user?</p>
            <table summary="account info view">
            <tr>
                <th>First Name</th>
                <td><%= @user.first_name%></td>
            </tr>
            <tr>
                <th>Last Name</th>
                <td><%= @user.last_name %></td>
            </tr>
            <tr>
                <th>Email</th>
                <td><%= @user.email%></td>
            </tr>
            </table>
            <div class="form-buttons">
                <%= f.submit("Delete User")%>
            </div>
        <% end %>
    </div>
</div>
</center>
<br/>

<div style = "text-align: center;">
    <%= link_to("<< Back to Users List", users_path, :class => 'back-link') %>
</div>

app/views/users/edit.html.erb
<% flash.each do |type, msg| %>
    <div style="color:red;">
    <%= msg %>
    </div>
<% end %>

<style>
body {
  background-color: rgb(200, 200, 200);
  opacity: 0.9;
  color: black;
}
table.center {
  margin-left:auto;
  margin-right:auto;
  color: black;
}
</style>

<h2 style = "text-align: center; margin-top:30px;">Admin | Edit User Info</h2>
<br/>

<center>
<div class="container" style="width: 450px; margin: auto; background-color: rgb(230, 230, 230); 
    border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000; padding-top:15px; padding-bottom:15px;">
    <div class="user edit">
        <%= form_for(@user, url: {action: "update"}) do |f| %>
            <table summary = "Book from fields">
                <tr>
                    <th><%= f.label :email %></th>
                    <td><%= f.text_field(:email) %></td>
                </tr>
                <tr>
                    <th><%= f.label :first_name %></th>
                    <td><%= f.text_field(:first_name) %></td>
                </tr>
                <tr>
                    <th><%= f.label :last_name %></th>
                    <td><%= f.text_field(:last_name) %></td>
                </tr>
                <tr>
                    <th><%= f.label :phone_number %></th>
                    <td><%= f.text_field(:phone_number) %></td>
                </tr>
                <tr>
                    <th><%= f.label :secondary_contact %></th>
                    <td><%= f.text_field(:secondary_contact) %></td>
                </tr>
                <tr>
                    <th><%= f.label :violation_counter %></th>
                    <td><%= f.text_field(:violation_counter) %></td>
                </tr>
                <tr>
                    <th><%= f.label :is_admin %></th>
                    <td><%= f.select(:is_admin, options_for_select([['No', false], ['Yes', true]]), { include_blank: false })%></td>
                </tr>
            </table>

            <div class="form-buttons" style="margin-top:15px;">
                <%= f.submit("Update User") %>
            </div>

        <% end %>
    </div>
</div>
</center>
<br/>

<div style = "text-align: center;">
    <%= link_to("<< Back to Users List", users_path, :class => 'back-link') %>
</div>

app/views/users/index.html.erb
<% flash.each do |type, msg| %>
    <div style="color:red;">
    <%= msg %>
    </div>
<% end %>
<br/>

<style>
body {
  background-color: rgb(200, 200, 200);
  opacity: 0.9;
  color: black;
}
table.listing {
  margin-left:auto;
  margin-right:auto;
  color: black;
}
</style>

<h2 style = "text-align: center; management-top:30px;">Admin User Management</h2>
<br/>

<div class="container" style="width: 920px; margin: auto; background-color: rgb(230, 230, 230); border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000;">
    <div class = "accounts index">
        <table class="listing" summary="Book Listings">
            <tr class="header">
                <th style="padding:0 15px;">ID</th>
                <th style="padding:0 15px;">First Name</th>
                <th style="padding:0 15px;">Last Name</th>
                <th style="padding:0 15px;">Email</th>
                <th style="padding:0 15px;">Violation Counter</th>
            </tr>

            <% @users.each do |user| %>
            <tr>
                <td style="padding:0 15px;"><%= user.id %></td>
                <td style="padding:0 15px;"><%= user.first_name %></td>
                <td style="padding:0 15px;"><%= user.last_name %></td>
                <td style="padding:0 15px;"><%= user.email %></td>
                <td style="padding:0 15px;"><%= user.violation_counter%></td>
                <td style="padding:0 15px;"class="actions">
                    <%= link_to("Show", user_path(user), :class => 'action show') %>
                    <%= link_to("Edit", edit_user_path(user), :class => 'action edit') %>
                    <%= link_to("Delete", delete_user_path(user), :class => 'action delete') %>
                </td>
            </tr>
            <% end %>
        </table>
    </div>
</div>
<br/>

<div style = "text-align: center; padding-bottom:20px;">
    <%= link_to("<< Back To Dashboard", edit_account_registration_path, :class => 'back-link') %>
</div>
<br/>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% flash.each do |type, msg| %>
    <div style="color:red;">
    <%= msg %>
    </div>
<% end %>

<style>
body {
  background-color: rgb(200, 200, 200);
  opacity: 0.9;
  color: black;
}
table.center {
  margin-left:auto;
  margin-right:auto;
  color: white;
}
</style>

<h2 style="text-align:center; margin-top:30px;">Admin | Showing User Info</h2>
<br/>

<center>
<div class="container" style="width: 450px; margin: auto; background-color: rgb(230, 230, 230); border-radius:10px; 
    outline: 10px black;  box-shadow: 0 0 2px #000000;">
    <div class="users show">      
        <table summary="account info view">
            <tr>
                <th>ID</th>
                <td><%= @user.id %></td>
            </tr>
            <tr>
                <th>First Name</th>
                <td><%= @user.first_name%></td>
            </tr>
            <tr>
                <th>Last Name</th>
                <td><%= @user.last_name %></td>
            </tr>
            <tr>
                <th>Email</th>
                <td><%= @user.email%></td>
            </tr>
            <tr>
                <th>Phone Number</th>
                <td><%= @user.phone_number %></td>
            </tr>
            <tr>
                <th>Secondary Contact</th>
                <td><%= @user.secondary_contact %></td>
            </tr>
            <tr>
                <th>Account Created</th>
                <td><%= @user.created_at %></td>
            </tr>
            <tr>
                <th>Recent Update</th>
                <td><%= @user.updated_at %></td>
            </tr>
            <tr>
                <th>Admin</th>
                <td><%= @user.is_admin %></td>
            </tr>
        </table>
    </div>
</div>
</center>
<br/>

<div style = "text-align: center;">
    <%= link_to("<< Back to Users List", users_path, :class => 'back-link') %>
</div>