config/routes.rb
Rails.application.routes.draw do
  # get 'equipments/index'
  # get 'equipments/show'
  # get 'equipments/new'
  # get 'equipments/edit'
  # get 'equipments/delete'
  # get 'equipments/equip_list'
  # get 'reservations/index'
  # get 'reservations/show'
  # get 'reservations/new'
  # get 'reservations/edit'
  # get 'reservations/delete'
  # get 'users/index'
  # get 'users/show'
  # get 'users/new'
  # get 'users/edit'
  # get 'users/delete'

  root to: "home#index"
  get 'home/index'
  
  devise_for :accounts
  
  # EQUIPMENT ROUTES (Non ID routes cannot go into rescources)
  get 'equipments/index'
  get 'equipments/equip_list'
  resources :equipments do
    member do
      get :check_out
      get :check_in
      get :show_for_members
      get :delete
    end
  end
 
  # RESERVATION ROUTES
  # get 'reservations/select_date'
  post 'reservations/equip_reserve'
  get 'reservations/reservation_log'
  get 'reservations/future_reservations'
  get 'reservations/reserve_item'
  get 'reservations/reservation_list'
  resources :reservations do
    member do
      get :delete
      get :cancel_item
      get :admin_cancel_item
    end
  end

  resources :users do
    member do
      get :delete
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'DJOA Equipment Tracker', root_path, class: 'navbar-brand'%>
    <!--<a class="navbar-brand" href="#">DJOA Equipment Tracker</a>-->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <!--<a class="nav-link active" aria-current="page" href="#">Home</a>-->
          <%= link_to 'Home', root_path, class: 'nav-link active'%>
        </li>

        <% if account_signed_in? %>

            <li class="nav-item">
              <%= link_to 'Dashboard', edit_account_registration_path, class: 'nav-link'%>
            </li>

            <li class="nav-item">
              <%= link_to 'Equipment', equipments_equip_list_path, class: 'nav-link'%>
            </li>

            <li class="nav-item">
              <%= link_to 'Reservations', reservations_path, class: 'nav-link'%> <!-- Take To Calendar -->
            </li>

            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_account_session_path, method: :delete, class: 'nav-link'%>
            </li>

        <% end %>

        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>