config/routes.rb
Rails.application.routes.draw do
  # get 'equipments/index'
  # get 'equipments/show'
  # get 'equipments/new'
  # get 'equipments/edit'
  # get 'equipments/delete'
  # get 'equipments/equip_list'
  # get 'reservations/index'
  # get 'reservations/show'
  # get 'reservations/new'
  # get 'reservations/edit'
  # get 'reservations/delete'
  # get 'users/index'
  # get 'users/show'
  # get 'users/new'
  # get 'users/edit'
  # get 'users/delete'

  root to: "home#index"
  get 'home/index'
  
  devise_for :accounts
  
  # EQUIPMENT ROUTES (Non ID routes cannot go into rescources)
  get 'equipments/index'
  get 'equipments/equip_list'
  resources :equipments do
    member do
      get :check_out
      get :check_in
      get :show_for_members
      get :delete
    end
  end
 
  # RESERVATION ROUTES
  # get 'reservations/select_date'
  post 'reservations/equip_reserve'
  get 'reservations/reservation_log'
  get 'reservations/future_reservations'
  get 'reservations/reserve_item'
  get 'reservations/reservation_list'
  resources :reservations do
    member do
      get :delete
      get :cancel_item
      get :admin_cancel_item
    end
  end

  resources :users do
    member do
      get :delete
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  # Establish relationship
  belongs_to :account, optional: true
  has_one :equipment

  # Scope Testing of Reservation Model
  # Not Implemented Yet

  # Validation Testing of Reservation Model
  validates :account_id, presence: true # Was commented out
  # validates :future_equip_id, presence: true
  validates :checkout_date, presence: true # Was commented out
  validates :checkin_date, presence: true # Was commented out
  # validates :event_description, presence: true
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # Account Authorization
  def auth_admin
    redirect_to(root_path) unless current_account.is_admin
  end

  before_action :authenticate_account!
  before_action :auth_admin, only: [:reservation_log]
  require 'date'

  ####################################

  def index
    # Create a new reservation for the date
    @reservation = Reservation.new

    # Display Reservations That Are Mine
    @reservations = Reservation.order('id DESC')
  end

  # Should stay empty
  def show
    # @reservation = Reservation.find(params[:id])
  end

  # Should stay empty
  def new
    # @reservation = Reservation.new
  end

  # Should stay empty
  def create
    # @reservation = Reservation.new(reservation_params)
    # if @reservation.save
    #   redirect_to(equipments_path)
    # else
    #   render('new')
    # end
  end

  # Should stay empty
  def edit
    # @reservation = Reservation.find(params[:id])
  end

  # Should stay empty
  def update
    # @reservation = Reservation.find(params[:id])
    # if @reservation.update(reservation_params)
    #   redirect_to(reservation_path(@reservation))
    # else
    #   render('edit')
    # end
  end

  # Should stay empty
  def delete
    # @reservation = Reservation.find(params[:id])
  end

  # Should stay empty
  def destroy
    # @reservation = Reservation.find(params[:id])
    # @reservation.destroy
    # redirect_to(reservations_path) # , notice:"#{@book.Title} Was Deleted !")
  end

  def equip_reserve
    # Use passed in date, check if there is no reservation for the same item on that day
    event_string = params[:reservation][:event_description]
    reserve_t = (params[:reservation][:checkout_date]).to_datetime
    # reserve_t = reserve_t.new_offset("-0600")

    return_t = reserve_t + 1.day
    @future_date = Reservation.new(event_description: event_string, checkout_date: reserve_t, checkin_date: return_t)

    # Display Equipment To Be Reserved
    @equipments = Equipment.order('id ASC')

    @avail_array = []
    # Make avaiable array
    reslist = Reservation.order('id DESC')
    @equipments.each do |equipment|
      item_avail = true
      reslist.each do |resv|
        if (resv.checkout_date <= reserve_t) && (return_t <= resv.checkin_date) && (resv.future_equip_id == equipment.id)
          item_avail = false
          break
        end
      end
      @avail_array.push(item_avail)
    end

    # Display Reservations That Are Mine
    @reservations = Reservation.order('id DESC')

    render('reservations/equip_reserve')
  end

  # Only admin access
  def reservation_log
    @reservations = Reservation.order('checkout_date DESC')
    render('reservations/equip_log')
  end

  # def future_reservations
  #   @reservations = Reservation.order('checkout_date ASC')
  # end

  def reserve_item
    # Use passed in date, check if there is no reservation for the same item on that day
    @event_string = params[:event]
    @future_date = params[:cd].to_datetime
    @return_date = @future_date + 1.day

    # ID of desired item
    @equipment = Equipment.find(params[:id])

    # Check if item is avail for the passed in day
    invalid_reservation = false
    @reservation_list = Reservation.order('id DESC') # Optimize for search speedup. WHERE future_equip_id != null.
    @reservation_list.each do |curr_res|
      # Check if theres a reservation with the same item on the same day or in reservation range.
      invalid_reservation = true if (curr_res.checkout_date <= @future_date) && (@future_date <= curr_res.checkin_date) && (curr_res.future_equip_id == @equipment.id)
    end

    # If invalid_reservation is still false, we can make a future reservation.
    if invalid_reservation == false
      @acc_id = current_account.id # Find current account and the wanted item
      @reservation = Reservation.new(account_id: @acc_id, future_equip_id: @equipment.id, checkout_date: @future_date,
                                     checkin_date: @return_date, event_description: @event_string)
      @reservation.future_equip_id = @equipment.id

      # Update Item Info For Equipment Log
      @reservation.saved_item = @equipment.name
      @reservation.renter_name = current_account.first_name + ' ' + current_account.last_name

      if @reservation.save
        # Sends the user a confirmation email for the reservation
        ReservationMailer.item_reservation(@equipment, @reservation, current_account).deliver_now
        flash[:alert] = 'Notice: Reservation Complete!'
      else
        flash[:alert] = 'Notice: Error making reservation!'
      end
    else
      flash[:alert] = 'Notice: Equipment item is already reserved on your day!'
    end
    redirect_to(reservations_path)
  end

  def reservation_list
    # Get Reservation List
    @reservations = Reservation.order('id ASC')
  end

  def cancel_item
    # Get reservation by its passed in id.
    @reservation = Reservation.find(params[:id])

    # Set the reservation future equip id to nil.
    @reservation.future_equip_id = nil

    # @reservation.account_id = nil

    # Protect
    @reservation.save

    # Delete the reservation (possibly).
    # Re-render
    redirect_to(reservations_path) # Possibly change to do a show action
    flash[:alert] = 'Notice: Reservation Cancelled!'
  end

  def admin_cancel_item
    # Get reservation by its passed in id.
    @reservation = Reservation.find(params[:id])

    # Set the reservation future equip id to nil.
    @reservation.future_equip_id = nil

    # @reservation.account_id = nil

    # Protect
    @reservation.save

    # Delete the reservation (possibly).
    # Re-render
    redirect_to(reservations_reservation_list_path) # Possibly change to do a show action
    flash[:alert] = 'Notice: Reservation Cancelled!'
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<table summary="Reservation form fields">
      <tr>
        <th>Event Description</th>
        <td><%= f.text_field(:event_description) %></td>
      </tr>
      <tr>
        <th>Checkout Date</th>
        <td><%= f.text_field(:checkout_date) %></td>
      </tr>
      <tr>
        <th>Checkin Date</th>
        <td><%= f.text_field(:checkin_date) %></td>
      </tr>
    </table>

app/views/reservations/delete.html.erb
<h1>Reservations#delete</h1>
<%= link_to("<< Back to List", reservations_path, :class => 'back-link') %>

<div class="reservations delete">
  <h2>Delete reservation</h2>

  <%= form_for(@reservation, :method => 'delete') do |f| %>


    <p>Are You Sure</p>

    <div class="form-buttons">
      <%= f.submit("Delete reservation") %>
    </div>

  <% end %>
</div>

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>

<%= link_to("<< Back to List", reservations_path, :class => 'back-link') %>

<div class="reservations edit">
  <h2>Edit Reservation</h2>

  <%= form_for(@reservation) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>


    <div class="form-buttons">
      <%= f.submit("Update Reservation") %>
    </div>

  <% end %>
</div>

app/views/reservations/equip_log.html.erb
<h2 style = "text-align: center; padding:15px;">History Of Reservations</h2>

<div style = "text-align: center; padding-bottom:20px;">
    <%= link_to("<< Back To Dashboard", edit_account_registration_path, :class => 'back-link') %>
</div>

<style>
body {
  background-color: rgb(200, 200, 200);
  opacity: 0.9;
  color: black;
}
table.listing {
  margin-left:auto;
  margin-right:auto;
  color: black;
}
</style>

<center>
<div class="container" style="width: 40%; margin: auto; background-color: rgb(230, 230, 230); border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000;">
    <div class="All Reservations">
        <table class="listing" summary="Reservation List">
            <tr class="header">
                <!-- <th style="padding:0 15px;"> ID </th> -->
                <th style="padding:0 15px;"> Renter Name </th>
                <th style="padding:0 15px;"> Equipment Name </th>
                <th style="padding:0 15px;"> Checkout Date </th>
                <th style="padding:0 15px;"> Checkin Date </th>
            </tr>
            <% @reservations.each do |reservation| %>
            <tr>
                <td style="padding:0 15px;"><%= reservation.renter_name%></td>
                <td style="padding:0 15px;"><%= reservation.saved_item%></td>
                <td style="padding:0 15px;"><%= reservation.checkout_date%></td>
                <td style="padding:0 15px;"><%= reservation.checkin_date%></td>
            </tr>
            <% end %>
        </table>
    </div>
</div>
</center>

app/views/reservations/equip_reserve.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<style>
body {
  background-color: rgb(200, 200, 200);
  opacity: 0.9;
  color: black;
}
table.listing {
  margin-left:auto;
  margin-right:auto;
  color: black;
}
</style>

<h1 style = "text-align: center; margin-top:30px;">Equipment Items That Can Be Reserved </h1>
<br/>

<p  style = "text-align: center;">Pick an aviable item for your selected date: <%= @future_date.checkout_date %></p>
<br/>

<center>
<div class="container" style="width: 1200px; margin: auto; background-color: rgb(230, 230, 230); 
  border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000; padding-bottom:15px; padding-top:15px;">
    <div class="reservation equipment choose">    
        <table class="listing" summary="Equipment List">
            <tr class="header">
                <th style="padding:0 15px;"> ID </th>
                <th style="padding:0 15px;"> Name </th>
                <th style="padding:0 15px;"> Description </th>
                <th style="padding:0 15px;"> Available </th>
                <th style="padding:0 15px;"> Reserved User </th>
                <th style="padding:0 15px;"> Reserve Date </th>
                <th style="padding:0 15px;"> Return By Date </th>
                <th style="padding:0 15px;"> Action </th>
            </tr>
            <% counter = 0%>
            <% @equipments.each do |equipment| %>
            <tr>
                <td style="padding:0 15px;"><%= equipment.id%></td>
                <td style="padding:0 15px;"><%= equipment.name%></td>
                <td style="padding:0 15px;"><%= equipment.description%></td>

                <td style="padding:0 15px;"><%= @avail_array[counter]%> </td>

                <td style="padding:0 15px;">
                <% if equipment.reservation%>
                <%= equipment.reservation.account.email %>
                <% end %>
                </td>

                <td style="padding:0 15px;">            
                <% if equipment.reservation%>
                <%= equipment.reservation.checkout_date %>
                <% end %>
                </td>

                <td style="padding:0 15px;">            
                <% if equipment.reservation%>
                <%= equipment.reservation.checkin_date %>
                <% end %>
                </td>

                <td style="padding:0 15px;"class="actions">
                    <!-- #link_to("Reserve", reservations_equip_reserve, :class => "action reserve_item" :method => 'post') -->
                    <!-- link_to("Reserve", reserve_item_reservation_path(equipment), :class => "action reserve_item") -->
                    <%= link_to("Reserve", reservations_reserve_item_path(id: equipment.id, event: @future_date.event_description, cd: @future_date.checkout_date, ci: @future_date.checkin_date), :class => "action reserve_item") %>
                </td>
            </tr>
            <% counter = counter + 1%>
            <% end %>
        </table>
    </div>
</div>
</center>
<br/>

<h4 style="text-align: center;">My Future Reservations</h4>
<br/>

<center>
<div class="container" style="width: 1000px; margin: auto; background-color: rgb(230, 230, 230); 
  border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000; padding-bottom:15px; padding-top:15px;">
    <div class="my equipments">
        <table class="listing" summary="Equipment List">
            <tr class="header">
                <th style="padding:0 15px;"> ID </th>
                <th style="padding:0 15px;"> Name </th>
                <th style="padding:0 15px;"> Description </th>
                <th style="padding:0 15px;"> Reserved Date </th>
                <th style="padding:0 15px;"> Return By Date </th>
                <th style="padding:0 15px;"> Actions </th>
            </tr>
            <% current_account.reservations.each do |reservation| %>
            <% if reservation.future_equip_id != nil %>
            <% @future_item = Equipment.find(reservation.future_equip_id) %>
            <tr>
                <td style="padding:0 15px;"><%= @future_item.id%></td>
                <td style="padding:0 15px;"><%= @future_item.name%></td>
                <td style="padding:0 15px;"><%= @future_item.description%></td>
                <td style="padding:0 15px;"><%= reservation.checkout_date %></td>
                <td style="padding:0 15px;"><%= reservation.checkin_date %></td>
                <td style="padding:0 15px;"class="actions">
                    <%= link_to("Cancel", cancel_item_reservation_path(reservation), :class => "action cancel_item") %>
                </td>
            </tr>
            <% end %>
            <% end %>
        </table>
    </div>
</div>
</center>
<br/>

app/views/reservations/future_reservations.html.erb
<h1>Reservations#index</h1>

<% flash.each do |type, msg| %>
    <div style="color:red;">
    <%= msg %>
    </div>
<% end %>
<br />

<div class="reservations index">

    <h2> Reservation </h2>

    <table class="listing" summary="Reservation List">
        <tr class="header">
            <th> ID </th>
            <th> Event Description </th>
            <th> Checkout Date </th>
            <th> Checkin Date </th>
            <th> Actions </th>
        </tr>
       <% @reservations.where('checkout_date >= ?', DateTime.now.utc).each do |reservation| %>
        <tr>
            <td style="padding:0 15px;"><%= reservation.id%></td>
            <td style="padding:0 15px;"><%= reservation.event_description%></td>
            <td style="padding:0 15px;"><%= reservation.checkout_date%></td>
            <td style="padding:0 15px;"><%= reservation.checkin_date %> </td>
            <td class="actions">
                <%= link_to("Show", reservation_path(reservation), :class => "action show") %>
                <%= link_to("Edit", edit_reservation_path(reservation), :class => "action edit") %>
                <%= link_to("Delete", delete_reservation_path(reservation), :class => "action delete") %>
            </td>
       </tr>
        <% end %>
    </table>
    <br/>
    <%= link_to("ADD NEW RESERVATION", new_reservation_path, :class => "action new")%>

</div>

app/views/reservations/index.html.erb
<style>
body {
  background-color: rgb(200, 200, 200);
  opacity: 0.9;
  color: black;
}
table.listing {
  margin-left:auto;
  margin-right:auto;
  color: black;
}
</style>

<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<h1 style = "text-align: center; margin-top:30px;">Equipment Reservations</h1>
<br/>

<center>
<div class="container" style="width: 500px; margin: auto; background-color: rgb(230, 230, 230); 
  border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000; padding-bottom:15px; padding-top:15px;">
    <div class="reservations index">
        <h3> Select a Date for Reservation </h3>
        <div class="reservation dates">
            <%= form_for(@reservation, :url => reservations_equip_reserve_path, :method => 'post') do |f| %>
                <table summary="date dropdown">
                    <tr>
                        <th><%= f.label "Reserve Date" %></th>
                        <td><%= f.date_field(:checkout_date, min: 8.days.from_now, max: 1.year.from_now)%></td>
                    </tr>
                    <tr>
                        <th><%= f.label "Event Description" %></th>
                        <td><%= f.text_field(:event_description) %></td>
                    </tr>
                </table>
                <div class="form-buttons">
                    <%= f.submit("Pick Date") %>
                </div>
            <% end %>
        </div>
        <br/>
    </div>
</div>
</center>
<br/>

<h4 style = "text-align: center;">My Future Reservations</h4>
<br/>

<center>
<div class="container" style="width: 1000px; margin: auto; background-color: rgb(230, 230, 230); 
  border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000; padding-bottom:15px; padding-top:15px;">
    <div class="my equipments">
        <table class="listing" summary="Equipment List">
            <tr class="header">
                <th style="padding:0 15px;"> ID </th>
                <th style="padding:0 15px;"> Name </th>
                <th style="padding:0 15px;"> Description </th>
                <th style="padding:0 15px;"> Reserved Date </th>
                <th style="padding:0 15px;"> Return By Date </th>
                <th style="padding:0 15px;"> Actions </th>
            </tr>
            <% current_account.reservations.each do |reservation| %>
            <% if reservation.future_equip_id != nil %>
            <% @future_item = Equipment.find(reservation.future_equip_id) %>
            <tr>
                <td style="padding:0 15px;"><%= @future_item.id%></td>
                <td style="padding:0 15px;"><%= @future_item.name%></td>
                <td style="padding:0 15px;"><%= @future_item.description%></td>
                <td style="padding:0 15px;"><%= reservation.checkout_date %></td>
                <td style="padding:0 15px;"><%= reservation.checkin_date %></td>
                <td style="padding:0 15px;"class="actions">
                    <%= link_to("Cancel", cancel_item_reservation_path(reservation), :class => "action cancel_item") %>
                </td>
            </tr>
            <% end %>
            <% end %>
        </table>
    </div>
</div>
</center>

app/views/reservations/new.html.erb
<h1>Reservations#new</h1>

<%= link_to("<< Back to List", reservations_path, :class => 'back-link') %>

<div class="reservations new">
  <h2>Create Reservation</h2>

  <%= form_for(@reservation, :url => reservations_path, :method => 'post') do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Reservation") %>
    </div>

  <% end %>
</div>

app/views/reservations/reservation_list.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<style>
body {
  background-color: rgb(200, 200, 200);
  opacity: 0.9;
  color: black;
}
table.listing {
  margin-left:auto;
  margin-right:auto;
  color: black;
}
</style>

<h1 style="text-align: center; margin-top:30px;"> Admin Reservation Management </h1>
<br/>

<center>
<div class="container" style="width: 1000px; margin: auto; background-color: rgb(230, 230, 230); 
    border-radius:10px; outline: 10px black;  box-shadow: 0 0 2px #000000; padding-bottom:15px; padding-top:15px;">
    <div class="my equipments">
        <table class="listing" summary="Equipment List">
            <tr class="header">
                <th style="padding:0 15px;"> ID </th>
                <th style="padding:0 15px;"> Rentee Name </th>
                <th style="padding:0 15px;"> Rentee Email </th>
                <th style="padding:0 15px;"> Item Name </th>
                <th style="padding:0 15px;"> Description </th>
                <th style="padding:0 15px;"> Reserved Date </th>
                <th style="padding:0 15px;"> Return By Date </th>
                <th style="padding:0 15px;"> Actions </th>
            </tr>
            <% @reservations.each do |reservation| %>
                <% if reservation.future_equip_id != nil %>
                <% @future_item = Equipment.find(reservation.future_equip_id) %>
                    <% @acc = Account.find(reservation.account_id) %>
                    <tr>
                        <td style="padding:0 15px;"><%= @future_item.id%></td>
                        <td style="padding:0 15px;"><%= @acc.first_name + " " + @acc.last_name%></td>
                        <td style="padding:0 15px;"><%= @acc.email%></td>
                        <td style="padding:0 15px;"><%= @future_item.name%></td>
                        <td style="padding:0 15px;"><%= @future_item.description%></td>
                        <td style="padding:0 15px;"><%= reservation.checkout_date %></td>
                        <td style="padding:0 15px;"><%= reservation.checkin_date %></td>
                        <td style="padding:0 15px;"class="actions">
                            <%= link_to("Cancel", admin_cancel_item_reservation_path(reservation), :class => "action cancel_item") %>
                        </td>
                    </tr>
                <% end %>
            <% end %>
        </table>
    </div>
</div>
</center>
<br/>

<div style = "text-align: center; padding-bottom:20px;">
    <%= link_to("<< Back To Dashboard", edit_account_registration_path, :class => 'action equip_list')%>
</div>
<br/>

app/views/reservations/select_date.html.erb
<h1>Equipment Reservations</h1>

<div class="reservations index">
    <h3> Select a Date for Reservation </h3>
    <div class="reservation dates">
        <%= form_for(@selected_date, :url => reservations_equip_reserve_path, :method => 'post') do |f| %>
            <table summary="date dropdown">
                <tr>
                    <th><%= f.label "Reserve Date" %></th>
                    <td><%= f.date_field(:date, value: @start_date, min: 0.days.ago, max: 1.year.from_now)%></td>
                </tr>
            </table>
            <div class="form-buttons">
                <%= f.submit("Pick Date") %>
            </div>
        <% end %>
    </div>
    <br/>
</div>

app/views/reservations/show.html.erb
<h1>Reservations#show</h1>

<%= link_to("<< Back to List", reservations_path, :class => 'back-link') %>

<div class="reservations show">
  <h2>Show Reservation</h2>

  <table summary="reservation detail view">
    <tr>
      <th>ID</th>
      <td><%= @reservation.id %></td>
    </tr>
    <tr>
      <th>Event Description</th>
      <td><%= @reservation.event_description %></td>
    </tr>
    <tr>
      <th>Checkout Date</th>
      <td><%= @reservation.checkout_date%></td>
    </tr>
    <tr>
      <th>Checkin Date</th>
      <td><%= @reservation.checkin_date %></td>
    </tr>

  </table>

</div>